### PR TITLE
Add asset loading perf info

### PR DESCRIPTION
**Pull request by tad1**
adds asset loading time information to `24_ColorSpaceTest` (see [#721](https://github.com/Devsh-Graphics-Programming/Nabla/pull/721) for more details)

### CODE REVIEW

**Comment by AnastaZIuk** [comment]
> in .\examples_tests\24_ColorSpaceTest dir run ctest -C Debug --progress --stop-on-failure --verbose; python .\calcPerf.py

do not add extra overhead to `ctest` command, add `--python` & `--perf-py` (+ rename the script to `perf.py`). If `--perf-py` is present you should execute the same thing but from cpp given `--python` interpreter path. Pass both arguments from CMake within `add_test` definition

**Comment by AnastaZIuk** [comment]
also, didn't you forget to commit `calcPerf.py`? I can't see it anywhere

**Comment by tad1** [comment]
the script code is in [721#22511](https://github.com/Devsh-Graphics-Programming/Nabla/pull/721#issuecomment-2251124582) comment.
I wrote this script to quickly get hands-on data in a readable format. I can add proper integration to the 24th example for saving perf times to file.

**Comment by AnastaZIuk** [comment]
> the script code is in [721#22511](https://github.com/Devsh-Graphics-Programming/Nabla/pull/721#issuecomment-2251124582) comment. I wrote this script to quickly get hands-on data in a readable format. I can add proper integration to the 24th example for saving perf times to file.

ah okay, please go ahead and add the integration

**Comment by AnastaZIuk** [comment]
> the script code is in [721#22511](https://github.com/Devsh-Graphics-Programming/Nabla/pull/721#issuecomment-2251124582) comment. I wrote this script to quickly get hands-on data in a readable format. I can add proper integration to the 24th example for saving perf times to file.

mergin current stuff, open the test integration within the executable in separate PR

**Pull request merged**
